DROP DATABASE IF EXISTS KeepIt4Me;
CREATE DATABASE KeepIt4Me;
USE KeepIt4Me;
DROP TABLE IF EXISTS Account;
CREATE TABLE Account(
AccountID TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
Username NVARCHAR(30) NOT NULL UNIQUE KEY,
Passwords NVARCHAR(50) NOT NULL,
FullName NVARCHAR(50) NOT NULL
);
DROP TABLE IF EXISTS `Targets`;
CREATE TABLE `Targets` (
TargetsID TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
TargetsName ENUM('Hoc_Tap','Suc_Khoe','Tai_Chinh','Khac') NOT NULL UNIQUE KEY
);
DROP TABLE IF EXISTS `Detail_Goal`;
CREATE TABLE `Detail_Goal`(
Detail_Goal_ID TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
AccountID TINYINT UNSIGNED NOT NULL,
NameDetail NVARCHAR(50) NOT NULL UNIQUE KEY,
Start_Day DATE,
End_Day DATE,

Status ENUM('Cong_Khai','Chi_Rieng_Toi') NOT NULL UNIQUE KEY,
FOREIGN KEY(AccountID) REFERENCES Account(AccountID)

);
DROP TABLE IF EXISTS `Detail_Mini`;
CREATE TABLE `Detail_Mini`(
Detail_Mini_ID TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
Detail_Goal_ID TINYINT UNSIGNED NOT NULL,
Detail_Mini_Name NVARCHAR(50) NOT NULL UNIQUE KEY,
Start_Day DATE,
End_Day DATE,
FOREIGN KEY(Detail_Goal_ID) REFERENCES `Detail_Goal`(Detail_Goal_ID)
);
